### ISSUE TITLE
properties panel must be resizable

### ISSUE THREAD

**Issue by hloydl** [Loydl/nc-bpm-app#1]
![image](https://user-images.githubusercontent.com/7716757/111883133-b1ceb080-89b9-11eb-8e6e-916c4324a816.png)

Also when switching between elements the width of the panel must be fixed

**Comment by herr-vogel** [comment]
added in https://github.com/Loydl/nc-bpm-app/commit/a44f2843242e9c574704bf786bbd8198dfbae917
