### ISSUE TITLE
change menu entry name to "New BPMN diagram" / "New DMN diagram"

### ISSUE THREAD

**Issue by hloydl** [Loydl/nc-bpm-app#2]
currently the menu looks like this: 
![image](https://user-images.githubusercontent.com/7716757/111885838-87d1ba00-89ca-11eb-8ef3-f89030c122b5.png)

**Comment by herr-vogel** [comment]
fixed in https://github.com/Loydl/nc-bpm-app/commit/98eddfb4e4e3ed34bd5a6cb2441e4ab793a1db71
